### PR TITLE
Mobile Views

### PR DESCRIPTION
**Pull request by wgranger**
This PR adds mobile views for the intermediate page. I took out `gatsby-image` for several items to allow images to disappear, resize using CSS depending on screen size.

Styles: https://projects.invisionapp.com/d/main#/console/15093515/355829492/preview

### CODE REVIEW

**Review by mcbouslog — APPROVED** [review]
LGTM! This is good to merge.

This is not related to this PR, but more of a general mobile design question; on a few common phones per Chrome dev tools the "Hey there, ..." line breaks, which moves the Galaxy Zoo and Share buttons off screen, not sure if that matters or if there's even an easy way to fix.

**Comment by wgranger** [comment]
No, this is a good point. I'll check that call to action on mobile sizes and resize accordingly.

**Comment by wgranger** [comment]
@beckyrother This is how the page looks on an iPhone 4/SE. Should we resize the styles again at this smaller screen size to have the buttons visible on load?
Screen Shot 2019-05-06 at 6 36 35 PM

**Comment by beckyrother** [comment]
I'm ok with this sizing. Can we use the bold version of Poppins for the headline though?

**Comment by wgranger** [comment]
Yep. I'll double check that is the bold version. Anything newer than an iPhone 5 should be big enough to view the buttons underneath.

**Comment by wgranger** [comment]
This should be good to go.

**Comment by beckyrother** [comment]
Is there a staging link?

**Comment by wgranger** [comment]
@beckyrother There is not. This repo has not been set up with staging links.

**Comment by mcbouslog** [comment]
~Sorry have been sitting on this a bit. I can merge and we can move on, but using Simulator it looks like the icon and title spacing might be off? Or let me know if different preferred method for testing.~

Edit: ^ was running wrong branch

**Comment by wgranger** [comment]
I was going to let Becky take a look locally first. Let's hold a until that happens. What mobile size is that you're running in the simulator?

**Comment by beckyrother** [comment]
Hi sorry I can look whenever y'all are ready

**Comment by mcbouslog** [comment]
That screenshot was from an iPhone XR 12.1

**Comment by mcbouslog** [comment]
Nope nope I was running master! SORRY

**Comment by mcbouslog** [comment]
LGTM

**Comment by wgranger** [comment]
This should be ready for a final review. I made a few changes to the CSS and content.

**Review by mcbouslog — APPROVED** [review]
Recent changes LGTM

**Pull request merged**
